### ISSUE TITLE
Sinara board support: m-labs 

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#139]
What are steps to enable ARTIQ support for Sinara hardware? 

# Sinara board support
White paper on clocking of Sinara hardware is [here](https://github.com/m-labs/sinara/wiki/SinaraClocking).

## ARTIQ v3
Many features of ARTIQ v3 are required for Sayma. Tracking for ARTIQ v3 is [here](https://github.com/m-labs/artiq/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.0). 
- [ ] DRTIO [ARTIQ #562](https://github.com/m-labs/artiq/issues/562)
    - [x] bare-bones demonstration of clock and data recovery using pair of KC705: [transceiver test](https://github.com/m-labs/drtio_transceiver_test)
    - [ ] depends on DMA  [ARTIQ #553](https://github.com/m-labs/artiq/issues/553) and [ARTIQ wiki](https://github.com/m-labs/artiq/wiki/DMA)

## ICs and configuration common to Sinara hardware
ICs common to several boards in the Sinara family follow. 
- monitoring/reset/LEDs (also available for WUT via IPMI)
    - [ ] I2C_MUX
    - [ ] LM75AIMM/NOPB I2C temperature monitors
    - [ ] MAX6642ATT90 temperature sensor
- [ ] Si5324 Precision Clock Multiplier/Jitter Attenuator
- [ ] MAX24287ETK+ Ethernet interface
- [ ] FT4232H Quad High Speed USB to Multipurpose UART/MPSSE IC
- LPC1776 hard-core ARM uP  --- not supported by m-labs
- [x] SATA pinout #157

## Kintex Ultrascale related
This is XCKU040 FPGA. Sinara tracking of this is #3; primary tracking is [ARTIQ #563](https://github.com/m-labs/artiq/issues/563).

### PCB_metlino
- LPC17762984 used for IPMI (ignored by m-labs)
- [ ] VHDCI support exposes IO that mimics Kasli peripheral interface #148
- RTM support exposes IO, clk in ARTIQ for future uses -- not supported in v0.1
- [ ] FMC configuration as in #148
- transceiver allocation for SFP/SATA/FAT_PIPE  as in #149

## Sayma
Software/gateware support for Sayma consists of the following parts. 

### phaser (analog output)
- [x] AD9154 DAC
- [x] jesd204b link to DAC on KC705
- [x] jesd204b dds demo [ARTIQ #580](https://github.com/m-labs/artiq/issues/580)
- [x] two-tone demo with kc705+ad9154 [ARTIQ #561](https://github.com/m-labs/artiq/issues/561)
- [ ] dsp/gateware features #2

### ingester (analog input) 
Analog input is not supported in m-labs support for v0.1. 
- AD9656 ADC -- not yet funded
- jesd204b input 
- jesd204b support for AD9656 
- basic servo (PID-like) [wiki](https://github.com/m-labs/sinara/wiki/Servo) 

### PCB_sayma_AMC
- LPC17762984 used for IPMI (ignored by m-labs)
- FMC configuration as in #148 

### PCB_sayma_RTM
- clock distribution (summarized [here](https://github.com/m-labs/sinara/issues/75))
    - [ ] HMC7043 SPI  14-Output Fanout Buffer for JESD204B
    - [ ] HMC830 SPI fractional-N PLL
- [ ] AD7194BCPZ analog mezzanine monitoring/calibration ADC #141 
- monitoring/reset/LEDs (also available for WUT via IPMI)
    - [ ] PCF8574ADW 8-Bit I/O Expander for I2C-Bus
    - [ ] 24LC64-I/MS EEPROM
- [ ] Sayma RTM/AMC FPGA link #140 

### PCB_mezzanine_analog_allaki
ARTIQ support is summarized in leading post in #144. High level:  
- The AMC-RTM FPGA link is needed. #140
- At a high level the users interacts with the analog mezzanines using TTL PHY and SPI PHY.
- "Someone has to look up where each pin is connected, dig into datasheets, write nice Python functions that wiggle them, write device database entries, test everything, go through a few rounds of yak shaving, write documentation, etc."

**Comment by jbqubit** [comment]
Support needed for AD7194BCPZ analog mezzanine monitoring/calibration ADC established in Issue #141.

**Comment by jbqubit** [comment]
@jordens @sbourdeauducq Please propose a road map for support of Sayma v0.1 hardware with emphasis on the LogiQ use case. Please include testing, delegation and responsibilities.

**Comment by jbqubit** [comment]
M-Labs hasn't made their own roadmap or checklist for Sayma support in the ARTIQ repository. I'd like to keep this open so I can roughly track what the steps are.

**Comment by sbourdeauducq** [comment]
Take our quote SINARA2 and the earlier UMD one - it's in there. Why do you want it in the ARTIQ repository?

**Comment by jbqubit** [comment]
A subset of the Sayma-dependencies is funded by ARL/UMD with the balance funded by Oxford. Other groups with an interest in Sayma don't have access to the contracts that fund the gateware/software work so are unaware about what's forthcoming. My previous efforts to introspect M-Labs development plans and make lists (eg above) were not well received. Please externalize your development trajectory and priorities for the benefit of the community. A simple check list worked reasonably well for eg Sayma hardware testing #224 and got some traction with DRTIO https://github.com/m-labs/artiq/issues/562. 

> Why do you want it in the ARTIQ repository?

@jordens said in #3 "Ack. Gateware and firmware can be tracked in artiq." As a bridge between Sayma and ARTIQ consider using the ARTIQ repo sayma tag https://github.com/m-labs/artiq/labels/area%3Asayma.

**Comment by hartytp** [comment]
My preferred way of handling this is to create an ARTIQ issue for each item that's funded. cf issues like [687](https://github.com/m-labs/artiq/issues/687). I'll post issues for other items we've funded (e.g. Novogorny Urukul) servo soon.

**Comment by sbourdeauducq** [comment]
Yes, one issue per item sounds good. Many already exist.

**Comment by jbqubit** [comment]
@hartytp I agree. One Issue per item is a good approach. @sbourdeauducq please do this for the UMD/ARL contracts. And choose a unifying tag and/or milestone.

**Comment by jbqubit** [comment]
@sbourdeauducq @jordens How do you want to handle this for UMD/ARL contracts?  I'm happy to create Issues as @hartytp did but I run the risk of dictating your workflow. Please comment.

**Comment by hartytp** [comment]
AFAICT, this has been done now.

**Comment by jbqubit** [comment]
Yes. Thank you @sbourdeauducq and @jordens. 

4.0 mile stones -- Sayma baseline support
https://github.com/m-labs/artiq/milestone/11

5.0 mile stones -- extended Sayma support 
https://github.com/m-labs/artiq/milestone/14
