### ISSUE TITLE
Sayma clock mezzanine interface 

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#23]
Interface between Sayma clock mezzanine and Sayma RTM motherboard. Same interface will be used for passive clock distribution board by WUT and on-mezzanine clock distribution by Oxford.

@cjbe @weidazh please forward to Harty

**geometry and mechanical**
- [x] what is minimum clock mezzanine geometry? WUT is presently assuming 43 x 80 x 4.2 mm
- [x] what IC sets/constrains this geometry
- [x] use same mounting to RTM motherboard as analog mezzanine interface #8? 
- [x] if space is tight on RTM motherboard, mezzanine could be moved to AMC motherboard or RF-backplane clock distribution slot -> not needed

**RF shield**
- [x] minimum interior height under shield lid

**PCB material/layers**
- [x] 4-layer PCB, top layer .020" Rogers 4350B
- [x] single ground for analog and digital

**connector choices**
- power and IO
  - [x] same 40-pin connector as analog mezzanine interface #8?  --> yes
- RF to/from motherboard
  - clk output: 
  - clk input:  

**power/IO header routing**
- digital
  - [x] does following approach in #8 work? --> yes
  - [x] how many IO are needed? --> in schematics
- digital and analog power, low noise (generated on AMC)
  - what voltage(s) are needed, current? 

**ADCs**
- are inputs on 24-bit calibration ADC desired ?

**Comment by hartytp** [comment]
@jbqubit the biggest factor in the geometry is the number of PLLs we'll need: if the 100MHz reference clock reaching the mezzanine meets the phase noise spec up to ~100kHz then we can lock the microwave VCO directly to it. If not, then we'll need to add an extra 100MHz clean-up oscillator, which makes the board bigger.

For the PLL board:
RF Input: 3.3V PECL square-wave, please (2 x SMP?)
RF Output: as input
Power: we need a clean +3V3 analog rail. +5V would be good too.

Is the "passive board" a mezzanine, which takes the front-panel SMA DAC clock input and connects it to the RTM? If so, can we give it a TCM2-43X+, ADCLK905 (or your favourite equivalent IC) & AC coupling caps to perform sine-square conversion. That way, the RTM only needs to be designed to take in a LVPECL square wave.

**Comment by dhslichter** [comment]
Can the mezzanine host LDOs to make its own clean 3.3V and 5V rails from a low noise +6VDC rail?  This would allow sharing of power supplies with the analog mezzanines, which would be nice.  One could use the same power/IO connector with a pin-compatible wiring.

**Comment by hartytp** [comment]
@dhslichter I'd be happy with putting LDOs on the clock mezzanine.

**Comment by gkasprow** [comment]
This is the right way of clean power generation.
I placed on the schematic the IO connector with same pinout as other
mezzanines

**Comment by sbouhabib** [comment]
I agree with greg the last LDO step should be on the mezzanine, and there shoul be a possiblity to get the hight possible voltage for future use (12V mains) even if it is not used at the moment, a lot of VCOs use 10V, 12 V even more, lacking this and even stepping up from 6V could be problematic in the future

**Comment by jbqubit** [comment]
@hartytp Do you want access to one of the 24-bit calibration ADCs?

**Comment by hartytp** [comment]
@jbqubit If there is a spare one, I think it would be a good idea.

**Comment by jbqubit** [comment]
@gkasprow Is this possible? I don't know if all the calibration ADCs are allocated.

**Comment by gkasprow** [comment]
At the moment we have all 16 ADC inputs connected to ADC/DAC mezzanines.
Shall I add another calibration ADC? Why would you need it?

**Comment by hartytp** [comment]
> Shall I add another calibration ADC? Why would you need it?

Don't bother. I have no immediate plans to use an ADC on the clock mezzanine. My comment was just that if there had been a spare ADC channel, then it might come in use later.
