### ISSUE TITLE
Sayma OpenMMC port milestone

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#437]
Sayma will initially ship with sufficient but inelegant software on the MMC. As discussed in #248 the plan is to port to OpenMMC. From a google hangout with @gkasprow today it sounds like this will be an involved process and is being tackled by Creotech. To facilitate tracking please do the following.
- [x] create a new Milestone called something like Sayma OpenMMC Port
- [x] create several Issues that cover atomic steps of the porting process
- [x] assign to whomever at Creotech is working on this

**Comment by jbqubit** [comment]
I've created https://github.com/m-labs/sinara/milestone/27
